version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: userservice
      MYSQL_USER: root
      MYSQL_PASSWORD: YourPassword
      MYSQL_ROOT_PASSWORD: YourPassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  user-service:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/userservice?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: YourPassword
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
